"""Synthetic, M5-shaped test fixture (NOT real M5 data).

Writes ``calendar.csv``, ``sales_train_evaluation.csv``, ``sell_prices.csv`` and ``SOURCE.json`` in
the original M5 layout, generated from a fixed seed, so tests and CI can exercise the M5 adapter
without the Kaggle files. Output is byte-identical for the same arguments.

Contents: 2 stores (CA_1, TX_1) × 2 departments (FOODS_3, HOBBIES_1) × 6 items, 1,100 days from
2011-01-29, with weekly and yearly seasonality, event uplift, a late product launch, and
week-level prices.
"""

from datetime import UTC, datetime
from pathlib import Path

import numpy as np
import pandas as pd

from industrial_ai.foundation.datasets import SourceType
from industrial_ai_warehouse.adapters.m5.source import (
    CALENDAR_FILE,
    PRICES_FILE,
    SALES_FILES,
    M5Source,
)

FIXTURE_SEED = 20260927
FIXTURE_START = "2011-01-29"
FIXTURE_DAYS = 1100
STORES = {"CA_1": "CA", "TX_1": "TX"}
DEPARTMENTS = {"FOODS_3": "FOODS", "HOBBIES_1": "HOBBIES"}
ITEMS_PER_DEPARTMENT = 6
LATE_LAUNCH_ITEM = "HOBBIES_1_006"
LATE_LAUNCH_DAY = 400
_EVENTS = {  # (month, day) -> (name, type)
    (2, 7): ("SuperBowl", "Sporting"),
    (2, 14): ("ValentinesDay", "Cultural"),
    (7, 4): ("IndependenceDay", "National"),
    (11, 24): ("Thanksgiving", "National"),
    (12, 25): ("Christmas", "National"),
}
_SECOND_EVENT = ("2012-12-25", "OrthodoxChristmasTest", "Religious")
"""One date with two events, to exercise ``event_name_2``."""


def write_m5_fixture(output: Path, seed: int = FIXTURE_SEED, days: int = FIXTURE_DAYS) -> None:
    """Generate the fixture files into ``output`` (created if needed)."""
    output.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed)
    calendar = _calendar(days)
    items = [f"{dept}_{n:03d}" for dept in DEPARTMENTS for n in range(1, ITEMS_PER_DEPARTMENT + 1)]
    sales = _sales(calendar, items, rng)
    prices = _prices(calendar, items, rng)
    calendar.to_csv(output / CALENDAR_FILE, index=False, lineterminator="\n")
    sales.to_csv(output / SALES_FILES[0], index=False, lineterminator="\n")
    prices.to_csv(output / PRICES_FILE, index=False, float_format="%.2f", lineterminator="\n")
    M5Source(
        dataset_id="m5_fixture",
        version="1",
        source_type=SourceType.FIXTURE,
        source="Synthetic M5-shaped fixture (not real M5 data)",
        source_url="",
        dataset_name="m5_like test fixture",
        license_notes="Synthetic data generated by the project; no third-party content.",
        created_at=datetime(2026, 9, 27, tzinfo=UTC),
        created_by=f"industrial_ai_warehouse.adapters.m5.fixture (seed={seed}, days={days})",
        notes="Layout matches M5; values are random. Never use for conclusions about real demand.",
    ).write(output)


def _calendar(days: int) -> pd.DataFrame:
    dates = pd.date_range(FIXTURE_START, periods=days, freq="D")
    week_index = np.arange(days) // 7  # M5 weeks start on Saturday; the fixture starts on one
    wday = ((dates.dayofweek + 2) % 7) + 1  # M5: 1 = Saturday … 7 = Friday
    frame = pd.DataFrame(
        {
            "date": dates.strftime("%Y-%m-%d"),
            "wm_yr_wk": [int(f"1{11 + w // 52:02d}{w % 52 + 1:02d}") for w in week_index],
            "weekday": dates.day_name(),
            "wday": wday,
            "month": dates.month,
            "year": dates.year,
            "d": [f"d_{i}" for i in range(1, days + 1)],
        }
    )
    names = [_EVENTS.get((d.month, d.day), (None, None)) for d in dates]
    frame["event_name_1"] = [n for n, _ in names]
    frame["event_type_1"] = [t for _, t in names]
    frame["event_name_2"] = None
    frame["event_type_2"] = None
    second = frame["date"] == _SECOND_EVENT[0]
    frame.loc[second, ["event_name_2", "event_type_2"]] = [_SECOND_EVENT[1], _SECOND_EVENT[2]]
    day = dates.day
    frame["snap_CA"] = (day <= 10).astype(int)
    frame["snap_TX"] = ((day <= 15) & (day % 2 == 1)).astype(int)
    frame["snap_WI"] = ((day <= 15) & (day % 2 == 0)).astype(int)
    return frame


def _sales(calendar: pd.DataFrame, items: list[str], rng: np.random.Generator) -> pd.DataFrame:
    dates = pd.to_datetime(calendar["date"])
    weekly = np.array([0.9, 0.85, 0.85, 0.9, 1.0, 1.25, 1.25])[dates.dt.dayofweek]
    yearly = 1 + 0.2 * np.sin(2 * np.pi * dates.dt.dayofyear.to_numpy() / 365.25)
    event = np.where(calendar["event_name_1"].notna(), 1.5, 1.0)
    rows = []
    for store, state in STORES.items():
        for item in items:
            dept = item.rsplit("_", 1)[0]
            level = rng.uniform(0.5, 20.0) if dept.startswith("FOODS") else rng.uniform(0.2, 4.0)
            mean = level * weekly * yearly * event
            dispersion = 2.0
            quantity = rng.negative_binomial(dispersion, dispersion / (dispersion + mean))
            if item == LATE_LAUNCH_ITEM:
                quantity[:LATE_LAUNCH_DAY] = 0
            rows.append(
                [
                    f"{item}_{store}_evaluation",
                    item,
                    dept,
                    DEPARTMENTS[dept],
                    store,
                    state,
                    *quantity,
                ]
            )
    columns = ["id", "item_id", "dept_id", "cat_id", "store_id", "state_id", *calendar["d"]]
    return pd.DataFrame(rows, columns=columns)


def _prices(calendar: pd.DataFrame, items: list[str], rng: np.random.Generator) -> pd.DataFrame:
    weeks = calendar.groupby("wm_yr_wk", sort=True)["d"].first()
    launch_week = calendar.loc[LATE_LAUNCH_DAY, "wm_yr_wk"]
    rows = []
    for store in STORES:
        for item in items:
            base = round(float(rng.uniform(1.0, 12.0)), 2)
            for week in weeks.index:
                if item == LATE_LAUNCH_ITEM and week < launch_week:
                    continue
                discount = 0.8 if rng.random() < 0.05 else 1.0
                rows.append([store, item, int(week), round(base * discount, 2)])
    return pd.DataFrame(rows, columns=["store_id", "item_id", "wm_yr_wk", "sell_price"])
