"""Synthetic operational schemas of the Warehouse pack, version 1.0.0 (docs/data-model.md §3).

M5 provides demand-side data only; these tables complete the Hybrid Validation Environment with
synthetic operations. ``derived.*`` tables are deterministic summaries of the reference data used
as generator inputs; ``ops.*`` tables are generated by the Synthetic Data Engine.
"""

from industrial_ai.foundation.datasets import DatasetSchema, DType, FieldSpec, ForeignKey

SCHEMA_VERSION = "1.0.0"


def _fk(field: str, ref_schema_id: str, ref_field: str | None = None) -> ForeignKey:
    return ForeignKey(
        fields=(field,), ref_schema_id=ref_schema_id, ref_fields=(ref_field or field,)
    )


# --- derived from reference data --------------------------------------------------------------

PRODUCT_PRICE = DatasetSchema(
    schema_id="derived.product_price",
    schema_version=SCHEMA_VERSION,
    fields=(
        FieldSpec(name="product_id", dtype=DType.STR),
        FieldSpec(name="avg_unit_price", dtype=DType.FLOAT, min=0.01, unit="USD"),
    ),
    primary_key=("product_id",),
    foreign_keys=(_fk("product_id", "retail.product"),),
    description="Mean weekly selling price per product (all selected stores and weeks).",
)

STORE_DEMAND = DatasetSchema(
    schema_id="derived.store_demand",
    schema_version=SCHEMA_VERSION,
    fields=(
        FieldSpec(name="store_id", dtype=DType.STR),
        FieldSpec(name="mean_daily_demand", dtype=DType.FLOAT, min=0, unit="units/day"),
    ),
    primary_key=("store_id",),
    foreign_keys=(_fk("store_id", "retail.store"),),
    description="Sum over products of each product's mean daily demand in the store.",
)

PLANNING_INPUT = DatasetSchema(
    schema_id="derived.planning_input",
    schema_version=SCHEMA_VERSION,
    fields=(
        FieldSpec(name="product_id", dtype=DType.STR),
        FieldSpec(name="store_id", dtype=DType.STR),
        FieldSpec(name="warehouse_id", dtype=DType.STR),
        FieldSpec(name="mean_daily_demand", dtype=DType.FLOAT, min=0, unit="units/day"),
        FieldSpec(name="lead_time_mean_days", dtype=DType.FLOAT, min=1, unit="days"),
        FieldSpec(name="initial_stock_target", dtype=DType.FLOAT, min=0, unit="units"),
    ),
    primary_key=("product_id", "warehouse_id"),
    foreign_keys=(
        _fk("product_id", "retail.product"),
        _fk("store_id", "retail.store"),
        _fk("warehouse_id", "ops.warehouse"),
    ),
    description=(
        "Per product and stocking point: mean daily demand over the recent active history, the "
        "supplier's mean lead time and the initial stock target mean_daily_demand x "
        "(lead time + order cycle / 2)."
    ),
)

# --- synthetic operations ---------------------------------------------------------------------

WAREHOUSE = DatasetSchema(
    schema_id="ops.warehouse",
    schema_version=SCHEMA_VERSION,
    fields=(
        FieldSpec(name="warehouse_id", dtype=DType.STR),
        FieldSpec(name="store_id", dtype=DType.STR),
        FieldSpec(name="capacity_units", dtype=DType.INT, min=1, unit="units"),
        FieldSpec(name="holding_cost_rate_annual", dtype=DType.FLOAT, min=0, max=1),
    ),
    primary_key=("warehouse_id",),
    foreign_keys=(_fk("store_id", "retail.store"),),
    description="Stocking point (single echelon: one per store).",
)

SUPPLIER = DatasetSchema(
    schema_id="ops.supplier",
    schema_version=SCHEMA_VERSION,
    fields=(
        FieldSpec(name="supplier_id", dtype=DType.STR),
        FieldSpec(name="order_cost", dtype=DType.FLOAT, min=0, unit="USD per order"),
        FieldSpec(name="min_order_qty", dtype=DType.INT, min=0, unit="units"),
    ),
    primary_key=("supplier_id",),
)

SUPPLIER_LEAD_TIME = DatasetSchema(
    schema_id="ops.supplier_lead_time",
    schema_version=SCHEMA_VERSION,
    fields=(
        FieldSpec(name="supplier_id", dtype=DType.STR),
        FieldSpec(name="lead_time_mean_days", dtype=DType.FLOAT, min=1, unit="days"),
        FieldSpec(name="lead_time_std_days", dtype=DType.FLOAT, min=0, unit="days"),
        FieldSpec(name="on_time_probability", dtype=DType.FLOAT, min=0, max=1),
    ),
    primary_key=("supplier_id",),
    foreign_keys=(_fk("supplier_id", "ops.supplier"),),
    description="Lead-time distribution per supplier; lead times are sampled per purchase order.",
)

PRODUCT_SUPPLIER = DatasetSchema(
    schema_id="ops.product_supplier",
    schema_version=SCHEMA_VERSION,
    fields=(
        FieldSpec(name="product_id", dtype=DType.STR),
        FieldSpec(name="supplier_id", dtype=DType.STR),
        FieldSpec(name="unit_cost", dtype=DType.FLOAT, min=0.01, unit="USD"),
        FieldSpec(name="case_pack", dtype=DType.INT, min=1, unit="units"),
    ),
    primary_key=("product_id",),
    foreign_keys=(_fk("product_id", "retail.product"), _fk("supplier_id", "ops.supplier")),
)

INITIAL_INVENTORY = DatasetSchema(
    schema_id="ops.initial_inventory",
    schema_version=SCHEMA_VERSION,
    fields=(
        FieldSpec(name="product_id", dtype=DType.STR),
        FieldSpec(name="warehouse_id", dtype=DType.STR),
        FieldSpec(name="on_hand_units", dtype=DType.INT, min=0, unit="units"),
        FieldSpec(name="on_order_units", dtype=DType.INT, min=0, unit="units"),
    ),
    primary_key=("product_id", "warehouse_id"),
    foreign_keys=(_fk("product_id", "retail.product"), _fk("warehouse_id", "ops.warehouse")),
    description="Inventory state at the start of the simulation horizon.",
)

REPLENISHMENT_POLICY = DatasetSchema(
    schema_id="ops.replenishment_policy",
    schema_version=SCHEMA_VERSION,
    fields=(
        FieldSpec(name="product_id", dtype=DType.STR),
        FieldSpec(name="warehouse_id", dtype=DType.STR),
        FieldSpec(name="review_period_days", dtype=DType.INT, min=1, unit="days"),
        FieldSpec(name="order_cycle_days", dtype=DType.INT, min=1, unit="days"),
        FieldSpec(name="target_service_level", dtype=DType.FLOAT, min=0.5, max=0.9999),
    ),
    primary_key=("product_id", "warehouse_id"),
    foreign_keys=(_fk("product_id", "retail.product"), _fk("warehouse_id", "ops.warehouse")),
    description=(
        "Strategy-independent planning settings; each replenishment strategy derives its own "
        "parameters (reorder point, safety stock, order-up-to level) from these at run time."
    ),
)

SYNTHETIC_DEMAND = DatasetSchema(
    schema_id="ops.synthetic_demand",
    schema_version=SCHEMA_VERSION,
    fields=(
        FieldSpec(name="date", dtype=DType.DATE),
        FieldSpec(name="product_id", dtype=DType.STR),
        FieldSpec(name="store_id", dtype=DType.STR),
        FieldSpec(name="quantity", dtype=DType.INT, min=0, unit="units"),
        FieldSpec(name="scenario_id", dtype=DType.STR),
    ),
    primary_key=("date", "product_id", "store_id"),
    foreign_keys=(_fk("product_id", "retail.product"), _fk("store_id", "retail.store")),
    time_index="date",
    entity_keys=("product_id", "store_id"),
    description="Scenario-specific synthetic daily demand over the simulation horizon.",
)

OPERATIONS_SCHEMAS: dict[str, DatasetSchema] = {
    "product_price": PRODUCT_PRICE,
    "store_demand": STORE_DEMAND,
    "warehouse": WAREHOUSE,
    "supplier": SUPPLIER,
    "supplier_lead_time": SUPPLIER_LEAD_TIME,
    "product_supplier": PRODUCT_SUPPLIER,
    "planning_input": PLANNING_INPUT,
    "initial_inventory": INITIAL_INVENTORY,
    "replenishment_policy": REPLENISHMENT_POLICY,
}
"""Operational tables by bundle table name (synthetic demand is generated per scenario run)."""
